spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_details?useSSL=false
    username: root
    password: Sanju@123
    driver-class-name: com.mysql.cj.jdbc.Driver

#JPA Settings
  jpa:
    hibernate.ddl_auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect